SELECT A.ID AS ID, B.FISH_NAME AS FISH_NAME, A.LENGTH AS LENGTH
FROM FISH_INFO A INNER JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO A2
    WHERE A2.FISH_TYPE = A.FISH_TYPE
)
ORDER BY A.ID